apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  generation: 9
  labels:
    app: csh-map
  name: guh
spec:
  tags:
  - annotations:
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/imported-from: computersciencehouse/csh-map
    from:
      kind: DockerImage
      name: 172.30.132.75:5000/map/csh-map:latest
    generation: 8
    importPolicy:
      scheduled: true
    name: latest
